// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultProjectsDir() {
  return window['go']['app']['App']['DefaultProjectsDir']();
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['app']['App']['ListProjects'](arg1);
}

export function ListSubdirs(arg1) {
  return window['go']['app']['App']['ListSubdirs'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['app']['App']['LoadProject'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['app']['App']['OpenPath'](arg1);
}

export function PathExists(arg1) {
  return window['go']['app']['App']['PathExists'](arg1);
}

export function PreviewExport(arg1, arg2) {
  return window['go']['app']['App']['PreviewExport'](arg1, arg2);
}

export function PreviewScan(arg1) {
  return window['go']['app']['App']['PreviewScan'](arg1);
}

export function RunExport(arg1, arg2) {
  return window['go']['app']['App']['RunExport'](arg1, arg2);
}

export function SaveProject(arg1, arg2) {
  return window['go']['app']['App']['SaveProject'](arg1, arg2);
}

export function ScanProject(arg1) {
  return window['go']['app']['App']['ScanProject'](arg1);
}

export function ScanSensitive(arg1, arg2) {
  return window['go']['app']['App']['ScanSensitive'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['app']['App']['SelectDirectory'](arg1);
}

export function SerializeYAML(arg1) {
  return window['go']['app']['App']['SerializeYAML'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['app']['App']['SetLocale'](arg1);
}

export function ValidateConfig(arg1) {
  return window['go']['app']['App']['ValidateConfig'](arg1);
}
