// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {config} from '../models';

export function DeleteProject(arg1:string):Promise<void>;

export function ListProjects(arg1:string):Promise<Array<app.ProjectSummary>>;

export function LoadProject(arg1:string):Promise<config.ProjectConfig>;

export function RunExport(arg1:config.ProjectConfig,arg2:app.ExportOptions):Promise<app.ExportResult>;

export function SaveProject(arg1:string,arg2:config.ProjectConfig):Promise<void>;

export function ScanProject(arg1:config.ProjectConfig):Promise<Array<app.FileInfo>>;
