// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['app']['App']['ListProjects'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['app']['App']['LoadProject'](arg1);
}

export function RunExport(arg1, arg2) {
  return window['go']['app']['App']['RunExport'](arg1, arg2);
}

export function SaveProject(arg1, arg2) {
  return window['go']['app']['App']['SaveProject'](arg1, arg2);
}

export function ScanProject(arg1) {
  return window['go']['app']['App']['ScanProject'](arg1);
}
